* Wat Programming Language

/Wat/ is an ultra-lightweight, advanced, and practical Lisp for
JavaScript, in which everything is first-class: syntax, control, and
data.  Syntax is based on lexically-scoped fexprs and first-class
environments, subsuming ordinary procedures and hygienic macros.
Control is based on delimited continuations, subsuming all
computational effects such as lightweight threads and monads.  Data
uses first-class types that allow generic programming over built-in as
well as user-defined types.  The language is rounded out with Common
Lisp features such as generic functions, restartable exceptions,
dynamically-bound variables, a numerical tower, and common data
structures such as hashtables.  The Wat runtime is implemented in only
500 lines of JavaScript and evaluates the prelude and a REPL written
in Wat in under 50ms in common JavaScript interpreters.

The Wat Language Manual is online at
<http://manuel.github.com/wat-js/doc/manual.html>.

** Wat on the WWW

Try Wat online with a rudimentary REPL at
<http://manuel.github.com/wat-js/browser/>.

** Wat on the PC

Execute =./wat=.  (Requires SpiderMonkey command-line JS interpreter.)

** Current Status

Wat is actively being developed by Manuel Simoni (msimoni@gmail.com)
and currently only for the brave.

** Licensing

=wat-js= is released under the MIT License.
